name: Build NPM Package
on:
  push:
    branches:
      - feature/git-workflows
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./
    concurrency:
      group: npm-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Nodejs and npm
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Setup yarn
        run: npm install -g yarn

      - name: Setup Nodejs with yarn caching
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: yarn

      - name: Install root node dependencies
        run: yarn

      - name: Download Skia Binary Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: "build-skia.yml"
          path: artifacts

      - name: Copy Artifacts to libs folder
        run: yarn workflow-copy-libs

      - name: Copy Skia Headers
        run: yarn copy-skia-headers

      - name: Build NPM Package
        run: yarn build-npm

      - name: Upload artifacts - NPM Package
        uses: actions/upload-artifact@v2
        with:
          name: npm-package
          path: ${{ env.WORKING_DIRECTORY }}/dist/*
